/*
//example Custom Template for ODST armour
class ARMCO__ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour ()";
  hiddenSelections[] = {};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {};
    hiddenSelectionsTextures[] = {};
  };
};
*/
class ARMCO_Addy_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Addy)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTCQBRight",
                        "AS_ODSTRight",
                        "AS_ODSTSniperLeft",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_BR",
                        "AP_Canteen",
                        "AP_GL",
                        "AP_Knife",
                        "AP_MGThigh",
                        "AP_AR",
                        "AP_Pack",
                        "AP_Pistol",
                        "AP_Rounds",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Thigh",
                        "AP_Frag",
                        "AP_Smoke",
                        "APO_AR",
                        "APO_BR",
                        "APO_Knife",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Addy_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Addy_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTCQBRight",
                          "AS_ODSTRight",
                          "AS_ODSTSniperLeft",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_BR",
                          "AP_Canteen",
                          "AP_GL",
                          "AP_Knife",
                          "AP_MGThigh",
                          "AP_AR",
                          "AP_Pack",
                          "AP_Pistol",
                          "AP_Rounds",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Thigh",
                          "AP_Frag",
                          "AP_Smoke",
                          "APO_AR",
                          "APO_BR",
                          "APO_Knife",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Addy_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Addy_co.paa"};
  };
};
class ARMCO_Belhun_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Belhun)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTRight",
                        "AS_ODSTSniperLeft",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_BR",
                        "AP_Canteen",
                        "AP_GL",
                        "AP_Knife",
                        "AP_MGThigh",
                        "AP_AR",
                        "AP_Pack",
                        "AP_Pistol",
                        "AP_Rounds",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Thigh",
                        "AP_Frag",
                        "AP_Smoke",
                        "APO_AR",
                        "APO_BR",
                        "APO_Knife",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Belhun_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Belhun_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Belhun_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTRight",
                          "AS_ODSTSniperLeft",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_BR",
                          "AP_Canteen",
                          "AP_GL",
                          "AP_Knife",
                          "AP_MGThigh",
                          "AP_AR",
                          "AP_Pack",
                          "AP_Pistol",
                          "AP_Rounds",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Thigh",
                          "AP_Frag",
                          "AP_Smoke",
                          "APO_AR",
                          "APO_BR",
                          "APO_Knife",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Belhun_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Belhun_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Belhun_co.paa"};
  };
};
class ARMCO_Blue_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Blue)";
  hiddenSelections[] = {"camo",           "camo2",
                        "camo3",          "camo4",
                        "camo5",          "A_Ghillie",
                        "AS_LargeLeft",   "AS_LargeRight",
                        "AS_MediumLeft",  "AS_MediumRight",
                        "AS_ODSTCQBLeft", "AS_ODSTCQBRight",
                        "AS_ODSTLeft",    "AS_ODSTSniperRight",
                        "AS_SmallLeft",   "AS_SmallRight",
                        "AP_BR",          "AP_Canteen",
                        "AP_GL",          "AP_MGThigh",
                        "AP_Pack",        "AP_Rounds",
                        "AP_SG",          "AP_SMG",
                        "AP_Sniper",      "AP_Thigh",
                        "AP_Frag",        "AP_AR",
                        "APO_BR",         "APO_SMG",
                        "APO_Sniper",     "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Blue_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Blue_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",           "camo2",
                          "camo3",          "camo4",
                          "camo5",          "A_Ghillie",
                          "AS_LargeLeft",   "AS_LargeRight",
                          "AS_MediumLeft",  "AS_MediumRight",
                          "AS_ODSTCQBLeft", "AS_ODSTCQBRight",
                          "AS_ODSTLeft",    "AS_ODSTSniperRight",
                          "AS_SmallLeft",   "AS_SmallRight",
                          "AP_BR",          "AP_Canteen",
                          "AP_GL",          "AP_MGThigh",
                          "AP_Pack",        "AP_Rounds",
                          "AP_SG",          "AP_SMG",
                          "AP_Sniper",      "AP_Thigh",
                          "AP_Frag",        "AP_AR",
                          "APO_BR",         "APO_SMG",
                          "APO_Sniper",     "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Blue_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Blue_co.paa"};
  };
};
class ARMCO_Boone_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Boone)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTCQBRight",
                        "AS_ODSTLeft",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_AR",
                        "AP_BR",
                        "AP_Canteen",
                        "AP_GL",
                        "AP_MGThigh",
                        "AP_AR",
                        "AP_Pack",
                        "AP_Pistol",
                        "AP_Rounds",
                        "AP_SG",
                        "AP_Sniper",
                        "APO_AR",
                        "APO_BR",
                        "APO_Knife",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Boone_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Boone_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTCQBRight",
                          "AS_ODSTLeft",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_AR",
                          "AP_BR",
                          "AP_Canteen",
                          "AP_GL",
                          "AP_MGThigh",
                          "AP_AR",
                          "AP_Pack",
                          "AP_Pistol",
                          "AP_Rounds",
                          "AP_SG",
                          "AP_Sniper",
                          "APO_AR",
                          "APO_BR",
                          "APO_Knife",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Boone_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Boone_co.paa"};
  };
};
class ARMCO_Burford_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Burford)";
  hiddenSelections[] = {"camo",           "camo2",
                        "camo3",          "camo4",
                        "camo5",          "A_Ghillie",
                        "AS_LargeLeft",   "AS_LargeRight",
                        "AS_MediumLeft",  "AS_MediumRight",
                        "AS_ODSTCQBLeft", "AS_ODSTCQBRight",
                        "AS_ODSTLeft",    "AS_ODSTSniperRight",
                        "AS_SmallLeft",   "AS_SmallRight",
                        "AP_BR",          "AP_Canteen",
                        "AP_GL",          "AP_MGThigh",
                        "AP_Pack",        "AP_Rounds",
                        "AP_SG",          "AP_SMG",
                        "AP_Sniper",      "AP_Thigh",
                        "AP_Frag",        "AP_AR",
                        "APO_BR",         "APO_SMG",
                        "APO_Sniper",     "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Burford_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Burford_co.paa"};
  class ItemInfo : ItemInfo {
    "camo", "camo2", "camo3", "camo4", "camo5", "A_Ghillie", "AS_LargeLeft",
        "AS_LargeRight", "AS_MediumLeft", "AS_MediumRight", "AS_ODSTCQBLeft",
        "AS_ODSTCQBRight", "AS_ODSTLeft", "AS_ODSTSniperRight", "AS_SmallLeft",
        "AS_SmallRight", "AP_BR", "AP_Canteen", "AP_GL", "AP_MGThigh",
        "AP_Pack", "AP_Rounds", "AP_SG", "AP_SMG", "AP_Sniper", "AP_Thigh",
        "AP_Frag", "AP_AR", "APO_BR", "APO_SMG", "APO_Sniper",
        "CustomKit_Scorch"
  };
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Burford_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Burford_co.paa"};
};
}
;
class ARMCO_Cheese_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Cheese)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTLeft",
                        "AS_ODSTRight",
                        "AS_ODSTSniperLeft",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_AR",
                        "AP_BR",
                        "AP_GL",
                        "AP_MGThigh",
                        "AP_AR",
                        "AP_Pack",
                        "AP_Rounds",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Thigh",
                        "AP_Frag",
                        "APO_BR",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Cheese_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Cheese_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Cheese_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTLeft",
                          "AS_ODSTRight",
                          "AS_ODSTSniperLeft",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_AR",
                          "AP_BR",
                          "AP_GL",
                          "AP_MGThigh",
                          "AP_AR",
                          "AP_Pack",
                          "AP_Rounds",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Thigh",
                          "AP_Frag",
                          "APO_BR",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Cheese_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Cheese_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Cheese_co.paa"};
  };
};
class ARMCO_Ciro_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Ciro)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTCQBRight",
                        "AS_ODSTLeft",
                        "AS_ODSTSniperRight",
                        "AS_ODSTSniperLeft",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_AR",
                        "AP_BR",
                        "AP_Canteen",
                        "AP_GL",
                        "AP_Knife",
                        "AP_MGThigh",
                        "AP_AR",
                        "AP_Pack",
                        "AP_Rounds",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Thigh",
                        "AP_Smoke",
                        "AP_Frag",
                        "APO_BR",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Ciro_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Ciro_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Ciro_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTCQBRight",
                          "AS_ODSTLeft",
                          "AS_ODSTSniperRight",
                          "AS_ODSTSniperLeft",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_AR",
                          "AP_BR",
                          "AP_Canteen",
                          "AP_GL",
                          "AP_Knife",
                          "AP_MGThigh",
                          "AP_AR",
                          "AP_Pack",
                          "AP_Rounds",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Thigh",
                          "AP_Smoke",
                          "AP_Frag",
                          "APO_BR",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Ciro_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Ciro_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Ciro_co.paa"};
  };
};
class ARMCO_Darkness_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Darkness)";
  hiddenSelections[] = {"camo",           "camo2",
                        "camo3",          "camo4",
                        "camo5",          "A_Ghillie",
                        "AS_LargeLeft",   "AS_LargeRight",
                        "AS_MediumLeft",  "AS_MediumRight",
                        "AS_ODSTCQBLeft", "AS_ODSTCQBRight",
                        "AS_ODSTLeft",    "AS_ODSTSniperRight",
                        "AS_SmallLeft",   "AS_SmallRight",
                        "AP_AR",          "AP_BR",
                        "AP_Canteen",     "AP_Knife",
                        "AP_GL",          "AP_AR",
                        "AP_Pack",        "AP_Rounds",
                        "AP_SG",          "AP_Sniper",
                        "AP_Frag",        "APO_AR",
                        "APO_BR",         "APO_Knife",
                        "APO_Sniper",     "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Darkness_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Darkness_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Darkness_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",           "camo2",
                          "camo3",          "camo4",
                          "camo5",          "A_Ghillie",
                          "AS_LargeLeft",   "AS_LargeRight",
                          "AS_MediumLeft",  "AS_MediumRight",
                          "AS_ODSTCQBLeft", "AS_ODSTCQBRight",
                          "AS_ODSTLeft",    "AS_ODSTSniperRight",
                          "AS_SmallLeft",   "AS_SmallRight",
                          "AP_AR",          "AP_BR",
                          "AP_Canteen",     "AP_Knife",
                          "AP_GL",          "AP_AR",
                          "AP_Pack",        "AP_Rounds",
                          "AP_SG",          "AP_Sniper",
                          "AP_Frag",        "APO_AR",
                          "APO_BR",         "APO_Knife",
                          "APO_Sniper",     "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Darkness_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Darkness_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Darkness_co.paa"};
  };
};
class ARMCO_Darman_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Darman)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTCQBRight",
                        "AS_ODSTLeft",
                        "AS_ODSTSniperLeft",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_BR",
                        "AP_Canteen",
                        "AP_GL",
                        "AP_Rounds",
                        "AP_Pack",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Smoke",
                        "AP_Frag",
                        "AP_AR",
                        "APO_BR",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Darman_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Darman_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Darman_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTCQBRight",
                          "AS_ODSTLeft",
                          "AS_ODSTSniperLeft",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_BR",
                          "AP_Canteen",
                          "AP_GL",
                          "AP_Rounds",
                          "AP_Pack",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Smoke",
                          "AP_Frag",
                          "AP_AR",
                          "APO_BR",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Darman_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Darman_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Darman_co.paa"};
  };
};
class ARMCO_Extortionist_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Extortionist)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTRight",
                        "AS_ODSTSniperLeft",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_BR",
                        "AP_MGThigh",
                        "AP_AR",
                        "AP_Pack",
                        "AP_Rounds",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Thigh",
                        "AP_Smoke",
                        "APO_BR",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Extortionist_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Extortionist_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Extortionist_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTRight",
                          "AS_ODSTSniperLeft",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_BR",
                          "AP_MGThigh",
                          "AP_AR",
                          "AP_Pack",
                          "AP_Rounds",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Thigh",
                          "AP_Smoke",
                          "APO_BR",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Extortionist_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Extortionist_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Extortionist_co."
        "paa"};
  };
};
class ARMCO_Garfield_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Garfield)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTCQBRight",
                        "AS_ODSTSniperLeft",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_AR",
                        "AP_BR",
                        "AP_GL",
                        "AP_AR",
                        "AP_Pack",
                        "AP_Rounds",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Frag",
                        "AP_Smoke",
                        "APO_AR",
                        "APO_Knife",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Garf_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Garf_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTCQBRight",
                          "AS_ODSTSniperLeft",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_AR",
                          "AP_BR",
                          "AP_GL",
                          "AP_AR",
                          "AP_Pack",
                          "AP_Rounds",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Frag",
                          "AP_Smoke",
                          "APO_AR",
                          "APO_Knife",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Garf_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Garf_co.paa"};
  };
};
class ARMCO_Merek_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Merek)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTRight",
                        "AS_ODSTSniperLeft",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_BR",
                        "AP_Canteen",
                        "AP_GL",
                        "AP_MGThigh",
                        "AP_AR",
                        "AP_Pack",
                        "AP_Pistol",
                        "AP_Rounds",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Thigh",
                        "APO_AR",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Merek_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Merek_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Merek_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTRight",
                          "AS_ODSTSniperLeft",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_BR",
                          "AP_Canteen",
                          "AP_GL",
                          "AP_MGThigh",
                          "AP_AR",
                          "AP_Pack",
                          "AP_Pistol",
                          "AP_Rounds",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Thigh",
                          "APO_AR",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Merek_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Merek_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Merek_co.paa"};
  };
};
class ARMCO_Mini_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Mini)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTCQBRight",
                        "AS_ODSTLeft",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_AR",
                        "AP_BR",
                        "AP_Knife",
                        "AP_MGThigh",
                        "AP_AR",
                        "AP_Pack",
                        "AP_Rounds",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Thigh",
                        "AP_Frag",
                        "AP_Smoke",
                        "APO_AR",
                        "APO_BR",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Mini_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Mini_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTCQBRight",
                          "AS_ODSTLeft",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_AR",
                          "AP_BR",
                          "AP_Knife",
                          "AP_MGThigh",
                          "AP_AR",
                          "AP_Pack",
                          "AP_Rounds",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Thigh",
                          "AP_Frag",
                          "AP_Smoke",
                          "APO_AR",
                          "APO_BR",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Mini_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Mini_co.paa"};
  };
};
class ARMCO_Nutters_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Nutters)";
  hiddenSelections[] = {"camo",           "camo2",
                        "camo3",          "camo4",
                        "camo5",          "A_Ghillie",
                        "AS_LargeLeft",   "AS_LargeRight",
                        "AS_MediumLeft",  "AS_MediumRight",
                        "AS_ODSTCQBLeft", "AS_ODSTCQBRight",
                        "AS_ODSTLeft",    "AS_ODSTSniperRight",
                        "AS_SmallLeft",   "AS_SmallRight",
                        "AP_AR",          "AP_BR",
                        "AP_Canteen",     "AP_GL",
                        "AP_MGThigh",     "AP_AR",
                        "AP_Pack",        "AP_Pistol",
                        "AP_Rounds",      "AP_SG",
                        "AP_SMG",         "AP_Sniper",
                        "AP_Thigh",       "AP_Smoke",
                        "AP_Frag",        "APO_AR",
                        "APO_BR",         "APO_SMG",
                        "APO_Sniper",     "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Nutters_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Nutters_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",           "camo2",
                          "camo3",          "camo4",
                          "camo5",          "A_Ghillie",
                          "AS_LargeLeft",   "AS_LargeRight",
                          "AS_MediumLeft",  "AS_MediumRight",
                          "AS_ODSTCQBLeft", "AS_ODSTCQBRight",
                          "AS_ODSTLeft",    "AS_ODSTSniperRight",
                          "AS_SmallLeft",   "AS_SmallRight",
                          "AP_AR",          "AP_BR",
                          "AP_Canteen",     "AP_GL",
                          "AP_MGThigh",     "AP_AR",
                          "AP_Pack",        "AP_Pistol",
                          "AP_Rounds",      "AP_SG",
                          "AP_SMG",         "AP_Sniper",
                          "AP_Thigh",       "AP_Smoke",
                          "AP_Frag",        "APO_AR",
                          "APO_BR",         "APO_SMG",
                          "APO_Sniper",     "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Nutters_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Nutters_co.paa"};
  };
};
class ARMCO_Raziel_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Raziel)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTCQBRight",
                        "AS_ODSTLeft",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_AR",
                        "AP_BR",
                        "AP_Canteen",
                        "AP_GL",
                        "AP_Knife",
                        "AP_MGThigh",
                        "AP_Pack",
                        "AP_Pistol",
                        "AP_Rounds",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Thigh",
                        "AP_Frag",
                        "AP_Smoke",
                        "APO_AR",
                        "APO_BR",
                        "APO_Knife",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Raz_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Raz_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTCQBRight",
                          "AS_ODSTLeft",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_AR",
                          "AP_BR",
                          "AP_Canteen",
                          "AP_GL",
                          "AP_Knife",
                          "AP_MGThigh",
                          "AP_Pack",
                          "AP_Pistol",
                          "AP_Rounds",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Thigh",
                          "AP_Frag",
                          "AP_Smoke",
                          "APO_AR",
                          "APO_BR",
                          "APO_Knife",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Raz_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Raz_co.paa"};
  };
};
class ARMCO_Reaper_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Reaper)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTRight",
                        "AS_ODSTSniperLeft",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_BR",
                        "AP_Canteen",
                        "AP_GL",
                        "AP_Knife",
                        "AP_MGThigh",
                        "AP_AR",
                        "AP_Pack",
                        "AP_Pistol",
                        "AP_Rounds",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Thigh",
                        "AP_Frag",
                        "AP_Smoke",
                        "APO_AR",
                        "APO_BR",
                        "APO_Knife",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Reaper_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Reaper_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Reaper_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTRight",
                          "AS_ODSTSniperLeft",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_BR",
                          "AP_Canteen",
                          "AP_GL",
                          "AP_Knife",
                          "AP_MGThigh",
                          "AP_AR",
                          "AP_Pack",
                          "AP_Pistol",
                          "AP_Rounds",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Thigh",
                          "AP_Frag",
                          "AP_Smoke",
                          "APO_AR",
                          "APO_BR",
                          "APO_Knife",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Reaper_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Reaper_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Reaper_co.paa"};
  };
};
class ARMCO_Red_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Red)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTCQBRight",
                        "AS_ODSTSniperLeft",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_BR",
                        "AP_Canteen",
                        "AP_GL",
                        "AP_Rounds",
                        "AP_Pack",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Smoke",
                        "AP_Frag",
                        "AP_AR",
                        "APO_BR",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_RedDragon_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_RedDragon_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_RedDragon_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTCQBRight",
                          "AS_ODSTSniperLeft",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_BR",
                          "AP_Canteen",
                          "AP_GL",
                          "AP_Rounds",
                          "AP_Pack",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Smoke",
                          "AP_Frag",
                          "AP_AR",
                          "APO_BR",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_RedDragon_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_RedDragon_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_RedDragon_co.paa"};
  };
};
class ARMCO_Runic_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Runic)";
  hiddenSelections[] = {"camo",           "camo2",
                        "camo3",          "camo4",
                        "camo5",          "A_Ghillie",
                        "AS_LargeLeft",   "AS_LargeRight",
                        "AS_MediumLeft",  "AS_MediumRight",
                        "AS_ODSTCQBLeft", "AS_ODSTCQBRight",
                        "AS_ODSTLeft",    "AS_ODSTSniperRight",
                        "AS_SmallLeft",   "AS_SmallRight",
                        "AP_AR",          "AP_BR",
                        "AP_Canteen",     "AP_GL",
                        "AP_Knife",       "AP_MGThigh",
                        "AP_AR",          "AP_Pack",
                        "AP_Rounds",      "AP_SG",
                        "AP_SMG",         "AP_Sniper",
                        "AP_Frag",        "APO_AR",
                        "APO_SMG",        "APO_Knife",
                        "APO_Sniper",     "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Runic_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Runic_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Runic_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",           "camo2",
                          "camo3",          "camo4",
                          "camo5",          "A_Ghillie",
                          "AS_LargeLeft",   "AS_LargeRight",
                          "AS_MediumLeft",  "AS_MediumRight",
                          "AS_ODSTCQBLeft", "AS_ODSTCQBRight",
                          "AS_ODSTLeft",    "AS_ODSTSniperRight",
                          "AS_SmallLeft",   "AS_SmallRight",
                          "AP_AR",          "AP_BR",
                          "AP_Canteen",     "AP_GL",
                          "AP_Knife",       "AP_MGThigh",
                          "AP_AR",          "AP_Pack",
                          "AP_Rounds",      "AP_SG",
                          "AP_SMG",         "AP_Sniper",
                          "AP_Frag",        "APO_AR",
                          "APO_SMG",        "APO_Knife",
                          "APO_Sniper",     "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Runic_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Runic_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Runic_co.paa"};
  };
};
class ARMCO_Shaw_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Shaw)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTCQBRight",
                        "AS_ODSTLeft",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_AR",
                        "AP_BR",
                        "AP_Canteen",
                        "AP_GL",
                        "AP_MGThigh",
                        "AP_AR",
                        "AP_Pack",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Thigh",
                        "AP_Frag",
                        "APO_AR",
                        "APO_Knife",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Shaw_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Shaw_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTCQBRight",
                          "AS_ODSTLeft",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_AR",
                          "AP_BR",
                          "AP_Canteen",
                          "AP_GL",
                          "AP_MGThigh",
                          "AP_AR",
                          "AP_Pack",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Thigh",
                          "AP_Frag",
                          "APO_AR",
                          "APO_Knife",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Shaw_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Shaw_co.paa"};
  };
};
class ARMCO_VJ_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (VJ)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTCQBRight",
                        "AS_ODSTLeft",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_AR",
                        "AP_BR",
                        "AP_Canteen",
                        "AP_GL",
                        "AP_Knife",
                        "AP_MGThigh",
                        "AP_AR",
                        "AP_Pack",
                        "AP_BR",
                        "AP_Rounds",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Pistol",
                        "AP_Smoke",
                        "APO_BR",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Super_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_VJ_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTCQBRight",
                          "AS_ODSTLeft",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_AR",
                          "AP_BR",
                          "AP_Canteen",
                          "AP_GL",
                          "AP_Knife",
                          "AP_MGThigh",
                          "AP_AR",
                          "AP_Pack",
                          "AP_BR",
                          "AP_Rounds",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Pistol",
                          "AP_Smoke",
                          "APO_BR",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Super_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_VJ_co.paa"};
  };
};
class ARMCO_Wolffe_ODST_Armor : ARMCO_Alpha_ODST_Armor {
  displayName = "[A][ARMCO] ODST Armour (Wolffe)";
  hiddenSelections[] = {"camo",
                        "camo2",
                        "camo3",
                        "camo4",
                        "camo5",
                        "A_Ghillie",
                        "AS_LargeLeft",
                        "AS_LargeRight",
                        "AS_MediumLeft",
                        "AS_MediumRight",
                        "AS_ODSTCQBLeft",
                        "AS_ODSTLeft",
                        "AS_ODSTRight",
                        "AS_ODSTSniperRight",
                        "AS_SmallLeft",
                        "AS_SmallRight",
                        "AP_BR",
                        "AP_Canteen",
                        "AP_GL",
                        "AP_Knife",
                        "AP_MGThigh",
                        "AP_AR",
                        "AP_Pack",
                        "AP_Pistol",
                        "AP_Rounds",
                        "AP_SG",
                        "AP_SMG",
                        "AP_Sniper",
                        "AP_Thigh",
                        "AP_Frag",
                        "AP_Smoke",
                        "APO_AR",
                        "APO_BR",
                        "APO_Knife",
                        "APO_SMG",
                        "APO_Sniper",
                        "CustomKit_Scorch"};
  hiddenSelectionsTextures[] = {
      "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
      "optre_unsc_units\army\data\armor_odst_co.paa",
      "armco_armours\data\odst\custom_armours\odst_legs_Wolffe_co.paa",
      "optre_unsc_units\army\data\ghillie_woodland_co.paa",
      "armco_armours\data\odst\custom_armours\odst_armor_Wolffe_co.paa"};
  class ItemInfo : ItemInfo {
    hiddenSelections[] = {"camo",
                          "camo2",
                          "camo3",
                          "camo4",
                          "camo5",
                          "A_Ghillie",
                          "AS_LargeLeft",
                          "AS_LargeRight",
                          "AS_MediumLeft",
                          "AS_MediumRight",
                          "AS_ODSTCQBLeft",
                          "AS_ODSTLeft",
                          "AS_ODSTRight",
                          "AS_ODSTSniperRight",
                          "AS_SmallLeft",
                          "AS_SmallRight",
                          "AP_BR",
                          "AP_Canteen",
                          "AP_GL",
                          "AP_Knife",
                          "AP_MGThigh",
                          "AP_AR",
                          "AP_Pack",
                          "AP_Pistol",
                          "AP_Rounds",
                          "AP_SG",
                          "AP_SMG",
                          "AP_Sniper",
                          "AP_Thigh",
                          "AP_Frag",
                          "AP_Smoke",
                          "APO_AR",
                          "APO_BR",
                          "APO_Knife",
                          "APO_SMG",
                          "APO_Sniper",
                          "CustomKit_Scorch"};
    hiddenSelectionsTextures[] = {
        "armco_armours\data\odst\custom_vest\vest_odst_Black_co.paa",
        "optre_unsc_units\army\data\armor_odst_co.paa",
        "armco_armours\data\odst\custom_armours\odst_legs_Wolffe_co.paa",
        "optre_unsc_units\army\data\ghillie_woodland_co.paa",
        "armco_armours\data\odst\custom_armours\odst_armor_Wolffe_co.paa"};
  };
};
