// this CfgPatches is for Backpacks
class CfgPatches {
  class ARMCO_Units_Army {
    units[] = {"ARMCO_Rucksack_Hard_Alpha",
               "ARMCO_Rucksack_Hard_Sabre",
               "ARMCO_Rucksack_Hard_Zulu",
               "ARMCO_Rucksack_Hard_Phoenix",
               "ARMCO_Rucksack_Hard_Medical",
               "ARMCO_Rucksack_Soft_Alpha",
               "ARMCO_Rucksack_Soft_Sabre",
               "ARMCO_Rucksack_Soft_Zulu",
               "ARMCO_Rucksack_Soft_Phoenix",
               "ARMCO_Rucksack_Soft_Medical",
               "ARMCO_Kitbag_Black",
               "ARMCO_Kitbag_Alpha",
               "ARMCO_Kitbag_Sabre",
               "ARMCO_Kitbag_Zulu",
               "ARMCO_Kitbag_Phoenix",
               "ARMCO_Kitbag_Medic",
               "ARMCO_Kitbag_Corpsman",
               "ARMCO_Kitbag_Medic_Camo",
               "ARMCO_Kitbag_Corpsman_Camo",
               "ARMCO_Kitbag_EOD",
               "ARMCO_Kitbag_Zulu_Camo",
               "ARMCO_Rucksack_Addy",
               "ARMCO_Rucksack_Belhun",
               "ARMCO_Rucksack_Blue",
               "ARMCO_Rucksack_Burford",
               "ARMCO_Rucksack_Boone",
               "ARMCO_Rucksack_Cheese",
               "ARMCO_Rucksack_Ciro",
               "ARMCO_Rucksack_Darkness",
               "ARMCO_Rucksack_Darman",
               "ARMCO_Rucksack_Extortionist",
               "ARMCO_Rucksack_Garfield",
               "ARMCO_Rucksack_Merek",
               "ARMCO_Rucksack_Mini",
               "ARMCO_Rucksack_Nutters",
               "ARMCO_Rucksack_Raziel",
               "ARMCO_Rucksack_Reaper",
               "ARMCO_Rucksack_Red",
               "ARMCO_Rucksack_Runic",
               "ARMCO_Rucksack_Shaw",
               "ARMCO_Rucksack_VJ",
               "ARMCO_Rucksack_Wolffe",
               "ARMCO_UNSC_PatrolCap_Army",
               "ARMCO_Beret",
               "ARMCO_Beret_Rifleman",
               "ARMCO_Beret_Medical",
               "ARMCO_Beret_TL",
               "ARMCO_Beret_Veteran",
               "ARMCO_Beret_Security",
               "ARMCO_Beret_EOD",
               "ARMCO_Beret_ODST",
               "ARMCO_PatrolCap_Hat",
               "ARMCO_Beret_Veteran",
               "ARMCO_Beret_Security",
               "ARMCO_Beret_EOD",
               "ARMCO_Beret_ODST",
               "ARMCO_PatrolCap_Hat"};
    weapons[] = {};
    requiredVersion = 0.1;
    requiredAddons[] = {
        "OPTRE_UNSC_Units", "A3_Weapons_F",           "OPTRE_Core",
        "ace_main",         "A3_Characters_F_BLUFOR", "OPTRE_Weapons"};
  };
};
